#!/bin/bash
x=$(date +%s)
for i in {1..1000}
do
	./random $((x * 34623 % 9045321)) > message_org
	./random $((x * 9373232 % 1245723)) > key
	
	cat message_org
	echo "--------------------"
	cat key
	echo

	cp -f message_org message_cp

	if ! .././xorc message_org key -s > message_cp;
	then
		echo -e "$i \e[1;31mfailed\e[0m"
		break
	fi
	
	if ! .././xorc - key < message_cp > out;
	then
		echo -e "$i \e[1;31mfailed\e[0m"
		break
	fi
	
	if ! diff message_org out;
	then
		echo -e "$i \e[1;31mtest: not the same\e[0m"
		break
	else
		echo -e "$i \e[1;32mgood\e[0m"
	fi
	echo
	
	x=$((x + 1))
done
